### ISSUE TITLE
Designer Support?

### ISSUE THREAD

**Issue by dazinator** [derfsplat/MiniMVP#1]
I tried to use this, but it appears to loose VS Form Designer support:

![image](https://cloud.githubusercontent.com/assets/3176632/4976860/7fd6ded6-68e1-11e4-99bc-75851719f29e.png)

Is this something I am doing wrong?

**Comment by elovelan** [comment]
This is due to [a limitation](https://connect.microsoft.com/VisualStudio/feedback/details/797279/win-forms-designer-error-when-inheriting-from-a-generic-form) in the way that WinForms works. It does not support generic classes that inherit from `Form`. A work-around is to create a dummy class that inherits from the generic View class. This **must** be in a separate file:

Dummy:

``` csharp
public class DialogForIPresentSampleDialog : Dialog<IPresentSampleDialog> {}
```

Dialog:

``` csharp
public partial class SampleDialog : DialogForIPresentSampleDialog, ISampleDialogView
{
    public SampleDialog()
    {
        InitializeComponent();
    }
}
```

@derfsplat think this warrants a **Readme** update?

**Comment by derfsplat** [comment]
Hi Darrell, Eric's right- it's a bug in the winforms designer MS is not going to fix.  The workaround does work, however it's not something I can bake into the framework since you have to be able to specify the `T` of your presenter on the view to get some of the magic to work.

Open to any bright ideas :smile: .

I'll update the readme in the meantime and provide a sample.

**Comment by dazinator** [comment]
Ok - I thought that would probably be the case :)

Before looking at this framework, I also came accross https://winformsmvp.codeplex.com/ which has the same limitation with the designer, and they have a couple of suggested workarounds. I think they do offer some non generic base classes if I have remembered correctly.

**Comment by derfsplat** [comment]
Readme Complete - https://github.com/derfsplat/MiniMVP#designer-support-when-inheriting-generic-view-classes.  Also added to samples.
